import {test} from 'node:test';import assert from 'node:assert/strict';
import {B,BLOCKS,FLUID,FLOW_LEVEL,flowId,isWater,isLava,DOORS,DOOR_FAMILY,HINGES} from '../src/world/blocks.js';
import {FluidSimulator,fluidDelay} from '../src/world/fluids.js';
import {shapeBoxes,collisionBoxes} from '../src/world/shapes.js';
import {nightLighting} from '../src/engine/night-visibility.js';
import {Inventory} from '../src/player/inventory.js';
import {getItem,makeStack} from '../src/crafting/items.js';
import {RECIPES,matchRecipe,recipeLayout} from '../src/crafting/recipes.js';
import {parseBackup,encodeBackup} from '../src/save/backup.js';
function world(){const blocks=new Map();const w={blocks,limit:32,getBlock(x,y,z){return blocks.get(`${x},${y},${z}`)??(y<=10?B.STONE:B.AIR);},
 isLoaded(x,z){return Math.abs(x)<this.limit&&Math.abs(z)<this.limit;},setBlock(x,y,z,id){const old=this.getBlock(x,y,z);if(old===id)return false;blocks.set(`${x},${y},${z}`,id);f.changed(x,y,z,old,id);return true;}};
 const f=new FluidSimulator(w);w.fluids=f;return w;}
function run(w,seconds=12){for(let i=0;i<seconds*10;i++)w.fluids.update(.1);}
function count(w,kind){return [...w.blocks.values()].filter(id=>FLUID[id]===kind).length;}
test('water levels spread seven cells on floor and stop, queue goes idle',()=>{const w=world();w.setBlock(0,11,0,B.WATER);run(w);
 assert.equal(w.getBlock(0,11,0),B.WATER);for(let i=1;i<=7;i++)assert.equal(FLOW_LEVEL[w.getBlock(i,11,0)],i);
 assert.equal(w.getBlock(8,11,0),B.AIR);assert.equal(count(w,1),113);assert.equal(w.fluids.queue.size,0);});
test('lava spreads only three cells and is slower',()=>{assert.ok(fluidDelay(2)>fluidDelay(1));const w=world();w.setBlock(0,11,0,B.LAVA);run(w,16);assert.equal(FLOW_LEVEL[w.getBlock(3,11,0)],3);assert.equal(w.getBlock(4,11,0),B.AIR);assert.equal(count(w,2),25);assert.equal(w.fluids.queue.size,0);});
test('fluid obeys a closed basin rather than flooding through its walls',()=>{const w=world();for(let i=-3;i<=3;i++){w.setBlock(i,11,-3,B.STONE);w.setBlock(i,11,3,B.STONE);w.setBlock(-3,11,i,B.STONE);w.setBlock(3,11,i,B.STONE);}w.setBlock(0,11,0,B.WATER);run(w);assert.equal(count(w,1),25);assert.equal(w.getBlock(4,11,0),B.AIR);});
test('opening a wall wakes adjacent fluid and fills the new passage',()=>{const w=world();for(let z=-8;z<=8;z++)w.setBlock(2,11,z,B.STONE);w.setBlock(0,11,0,B.WATER);run(w);assert.equal(w.getBlock(3,11,0),B.AIR);w.setBlock(2,11,0,B.AIR);run(w);assert.ok(isWater(w.getBlock(3,11,0)));});
test('waterfall prefers down, then spreads along floor',()=>{const w=world();w.setBlock(0,15,0,B.WATER);run(w);assert.equal(w.getBlock(1,15,0),B.AIR);assert.equal(w.getBlock(0,14,0),B.WATER_FALL);assert.ok(isWater(w.getBlock(1,11,0)));assert.equal(w.getBlock(1,12,0),B.AIR);});
test('blocking a waterfall makes it spread at the obstruction',()=>{const w=world();w.setBlock(0,15,0,B.WATER);run(w);w.setBlock(0,13,0,B.STONE);run(w);assert.ok(isWater(w.getBlock(1,14,0)));assert.equal(w.getBlock(0,13,0),B.STONE);});
test('source pickup makes all unsupported horizontal flow recede',()=>{const w=world();w.setBlock(0,11,0,B.WATER);run(w);w.setBlock(0,11,0,B.AIR);run(w,25);assert.equal(count(w,1),0);assert.equal(w.fluids.queue.size,0);});
test('removing waterfall source drains column and pool',()=>{const w=world();w.setBlock(0,15,0,B.WATER);run(w);w.setBlock(0,15,0,B.AIR);run(w,40);assert.equal(count(w,1),0);});
test('removing one source keeps streams supplied by another',()=>{const w=world();w.setBlock(0,11,0,B.WATER);w.setBlock(4,11,0,B.WATER);run(w);w.setBlock(0,11,0,B.AIR);run(w,25);assert.equal(w.getBlock(4,11,0),B.WATER);assert.ok(isWater(w.getBlock(0,11,0)));assert.equal(count(w,1),113);});
test('lava sources touching water become obsidian in either placement order',()=>{for(const reverse of [false,true]){const w=world();w.setBlock(reverse?1:0,11,0,reverse?B.WATER:B.LAVA);w.setBlock(reverse?0:1,11,0,reverse?B.LAVA:B.WATER);run(w,3);assert.equal(w.getBlock(0,11,0),B.OBSIDIAN);assert.equal(w.getBlock(1,11,0),B.WATER);}});
test('flowing lava touching water makes cobblestone, diagonal contact does not',()=>{const w=world();w.setBlock(0,11,0,flowId(2,1));w.setBlock(1,11,0,B.WATER);run(w,2);assert.equal(w.getBlock(0,11,0),B.COBBLESTONE);const d=world();d.setBlock(0,11,0,B.LAVA);d.setBlock(1,11,1,B.WATER);d.fluids.tick(0,11,0);assert.equal(d.getBlock(0,11,0),B.LAVA);});
test('flow never climbs upward or overwrites furniture',()=>{const w=world();w.setBlock(1,11,0,B.CHEST);w.setBlock(-1,11,0,B.GLASS_PANE);w.setBlock(0,11,0,B.WATER);run(w);assert.equal(w.getBlock(0,12,0),B.AIR);assert.equal(w.getBlock(1,11,0),B.CHEST);assert.equal(w.getBlock(-1,11,0),B.GLASS_PANE);});
test('unloaded columns are not mutated, resume after load',()=>{const w=world();w.limit=3;w.setBlock(1,11,0,B.WATER);run(w);assert.equal(w.getBlock(3,11,0),B.AIR);w.limit=32;for(const [k,id] of w.blocks)if(FLUID[id])w.fluids.schedule(...k.split(',').map(Number),FLUID[id]);run(w);assert.ok(isWater(w.getBlock(3,11,0)));});
test('simulation work capped per frame and dimension reset drops old queue',()=>{const w=world();w.fluids.maxWork=8;for(let i=-20;i<20;i++)w.setBlock(i,11,0,B.WATER);w.fluids.time=10;w.fluids.update(.1);assert.ok(w.fluids.processed<=8);w.fluids.reset();assert.equal(w.fluids.queue.size,0);});
test('night visibility gives brighter nights with zero daytime change',()=>{assert.ok(nightLighting(0,.75).boost>.35);assert.ok(nightLighting(0,1).ambient>nightLighting(0,0).ambient);assert.deepEqual(nightLighting(1,0),nightLighting(1,1));assert.equal(nightLighting(0,0).boost,0);});
test('night visibility is clamped and still works in rain',()=>{assert.deepEqual(nightLighting(0,999),nightLighting(0,1));assert.deepEqual(nightLighting(0,-1),nightLighting(0,0));assert.ok(nightLighting(0,.75,1).boost>0);});
test('birch/spruce doors toggle both orientations and preserve material',()=>{for(const id of [B.OAK_DOOR,B.BIRCH_DOOR,B.SPRUCE_DOOR])for(const closed of DOOR_FAMILY[id]){assert.equal(DOORS[DOORS[closed].toggle].toggle,closed);assert.equal(BLOCKS[closed].itemKey,BLOCKS[id].key);assert.equal(BLOCKS[DOORS[closed].toggle].solid,false);}});
test('panes join adjacent walls and panes into thin continuous windows',()=>{const id=B.GLASS_PANE;const a=shapeBoxes(id,(x,y,z)=>x?B.STONE:B.AIR);assert.equal(a.length,3);assert.ok(a.every(b=>b[5]-b[2]===.125));const b=shapeBoxes(id,(x,y,z)=>z?B.BLUE_GLASS_PANE:B.AIR);assert.equal(b.length,3);assert.ok(b.every(b=>b[3]-b[0]===.125));});
test('fences connect rails to walls; lanterns have narrow bodies',()=>{assert.equal(shapeBoxes(B.OAK_FENCE,()=>B.AIR).length,1);assert.equal(shapeBoxes(B.OAK_FENCE,()=>B.STONE).length,9);assert.equal(shapeBoxes(B.LANTERN,()=>0).length,4);});
test('gates/trapdoors toggle, orient and release collision when open',()=>{const w=world();for(const id of [B.OAK_GATE,B.OAK_TRAPDOOR]){w.setBlock(0,11,0,id);assert.ok(collisionBoxes(w,0,11,0).length);w.setBlock(0,11,0,HINGES[id].toggle);assert.equal(collisionBoxes(w,0,11,0).length,0);assert.equal(HINGES[HINGES[id].toggle].toggle,id);}});
test('all new building recipes match exact grids without shadowing',()=>{for(const key of ['birch_door','spruce_door','glass_pane','blue_glass_pane','amber_glass_pane','rose_glass_pane','blue_glass','amber_glass','rose_glass','oak_fence','oak_gate','oak_trapdoor','lantern','mosaic','basalt_tiles']){const r=RECIPES.find(r=>r.out.key===key);assert.ok(r,key);const grid=Array(9).fill(null);r.pattern.forEach((row,y)=>[...row].forEach((c,x)=>{if(c!==' ')grid[y*3+x]=makeStack(r.keys[c]);}));assert.equal(matchRecipe(grid,3)?.out.key,key,key);}});
test('source and flow block IDs survive real backup encoding without extra metadata',()=>{const rec={id:'fluid-test',name:'Fluid test',seed:1,gamemode:0,difficulty:2,data:{dim:0,time:.75,player:{pos:[0,65,0],yaw:0,pitch:0,health:20,hunger:20,saturation:5,air:300,xp:0,level:0,gamemode:0,difficulty:2,inventory:new Inventory().serialize()},world:Array.from({length:3},()=>({chunkEdits:[],be:[],sp:[],po:[]})),items:[]}};rec.data.world[0].chunkEdits=[['0,0',[0,B.WATER,1,flowId(1,7),2,B.WATER_FALL,3,B.LAVA_FALL,4,B.BIRCH_DOOR_X_OPEN,5,B.BLUE_GLASS_PANE]]];assert.deepEqual(parseBackup(encodeBackup(rec)),rec);});
